install:
- curl -sS https://getcomposer.org/installer | php
before_script:
- php composer.phar install -n
- php app/console d:m:f:l -n
- php app/console s:i:q -e prod -f
- php app/console s:i:r -e prod -b 2
script:
- vendor/bin/phpcs src/ --standard=PSR2
- vendor/bin/phpunit -c app/phpunit.xml
- vendor/bin/behat
