imports:
    - { resource: config_prod.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true
    spool:
        type: file
        path: %kernel.cache_dir%/spool
