integrated_content:
    resource: "@IntegratedContentBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_user:
    resource: "@IntegratedUserBundle/Resources/config/routing.xml"
    prefix: "/admin"

integrated_security:
    resource: "@IntegratedUserBundle/Resources/config/routing.security.xml"
    prefix: "/admin"

intergrated_workflow:
    resource: "@IntegratedWorkflowBundle/Resources/config/routing/workflow.xml"
    prefix: "/admin/workflow"